version: "3"

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  server1:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./server1/index.html:/usr/share/nginx/html/index.html

  server2:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./server2/index.html:/usr/share/nginx/html/index.html
